### ISSUE TITLE
Crashes due to failed communication with remote store 'daemon'

### ISSUE THREAD

**Issue by mweinelt** [mweinelt/mach-symbols-upload#6]
```
2023-01-09 02:00:01 [info     ] Channel advanced               channel=nixpkgs-unstable version=nixpkgs-23.05pre440754.0c9aadc8eff
2023-01-09 02:00:02 [info     ] Package found                  channel=nixpkgs-unstable hash=11kipyby3zyjpqllyf1rmgvk6vk24rz2 package=thunderbird-unwrapped store_path=/nix/store/11kipyby3zyjpqllyf1rmgvk6vk24rz2-thunderbird-unwrapped-102.6.0-symbols
error: cannot open connection to remote store 'daemon': error: writing to file: Broken pipe
Traceback (most recent call last):
  File "/nix/store/fm1bcnlxn5yvvf52cv1gwrkg282cf61q-mach-symbols-upload-20220816.0/bin/.mach-symbols-upload-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/b1w1m5fzfkqsgkm6lq85kwmfhcvhxxgs-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/b1w1m5fzfkqsgkm6lq85kwmfhcvhxxgs-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/nix/store/b1w1m5fzfkqsgkm6lq85kwmfhcvhxxgs-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/b1w1m5fzfkqsgkm6lq85kwmfhcvhxxgs-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/nix/store/fm1bcnlxn5yvvf52cv1gwrkg282cf61q-mach-symbols-upload-20220816.0/lib/python3.10/site-packages/mach_symbols_upload/__main__.py", line 171, in wrapper
    return asyncio.run(f(*args, **kwargs))
  File "/nix/store/nzgqxw4d875pgl1lji8n3q82x3bf7ldi-python3-3.10.8/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/nix/store/nzgqxw4d875pgl1lji8n3q82x3bf7ldi-python3-3.10.8/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/nix/store/fm1bcnlxn5yvvf52cv1gwrkg282cf61q-mach-symbols-upload-20220816.0/lib/python3.10/site-packages/mach_symbols_upload/__main__.py", line 250, in main
    assert len(files) == 1
AssertionError
```

**Comment by mweinelt** [comment]
Stopping the nix-daemon and restarting its socket fixed this.
